### ISSUE TITLE
Received custom options

### ISSUE THREAD

**Issue by jedisct1** [digineo/go-dhclient#7]
Hi,

Custom options can be requested, but is there a way to actually read them?

Looks like only the options present in the `Lease` structure are accessible. Is there another way?

Thanks in advance.

**Comment by corny** [comment]
Good point. Try the `other_options` branch. Do you have any suggestions how to solve better?

**Comment by jedisct1** [comment]
The `OtherOptions` field would be perfect. I don't think more is needed for custom options.
